name: Backup Database

on:
  push:
    branches:
      - main  # o la rama que estés utilizando

jobs:
  backup:
    runs-on: ubuntu-latest  # Usar un sistema basado en Linux en GitHub Actions

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Crear contenedor MySQL y realizar el backup
      - name: Create MySQL container and backup database
        run: |
          # Crear contenedor con base de datos "agencia"
          docker run --name workbench-contenedor -e MYSQL_ROOT_PASSWORD=$MYSQL_CONTENEDOR_PASSWORD -d mysql:latest
          
          # Crear el backup de la base de datos "agencia"
          docker exec workbench-contenedor mysqldump -u root -p$MYSQL_CONTENEDOR_PASSWORD agencia > backup.sql
          
          # Copiar el archivo de backup a la máquina local del flujo de trabajo
          docker cp workbench-contenedor:/backup.sql .

      # Paso 4: Crear otro contenedor MySQL y restaurar la base de datos
      - name: Restore backup to another MySQL container
        run: |
          # Crear contenedor de respaldo "workbench-backup"
          docker run --name workbench-backup -e MYSQL_ROOT_PASSWORD=$MYSQL_BACKUP_PASSWORD -d mysql:latest
          
          # Restaurar la base de datos "agencia_2"
          docker exec -i workbench-backup mysql -u root -p$MYSQL_BACKUP_PASSWORD agencia_2 < backup.sql
