name: Backup Database

on:
  push:
    branches:
      - main  # o la rama que estés utilizando

jobs:
  backup:
    runs-on: ubuntu-latest  # Usar un sistema basado en Linux en GitHub Actions

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Conectarse al contenedor 'workbench-contenedor' y hacer el backup
      - name: Backup Database from workbench-contenedor
        run: |
          # Copiar el backup de la base de datos "agencia" desde el contenedor
          docker exec workbench-contenedor mysqldump -u root -p$MYSQL_CONTENEDOR_PASSWORD agencia > backup.sql

      # Paso 3: Conectarse al contenedor 'workbench-backup' y restaurar la base de datos
      - name: Restore Backup to workbench-backup
        run: |
          # Restaurar el backup en la base de datos "agencia_2" dentro del contenedor de backup
          docker exec -i workbench-backup mysql -u root -p$MYSQL_BACKUP_PASSWORD agencia_2 < backup.sql
